#file: noinspection SpellCheckingInspection
run:
  concurrency: 4
  modules-download-mode: readonly

# https://golangci-lint.run/usage/configuration/#linters-configuration

issues:
  exclude-rules:
    - path: internal/converter/testdata/
      linters:
        - revive
    - path: _test\.go
      linters:
        - stylecheck
        - revive

linters-settings:
  mnd:
    ignored-files:
      - 'internal/converter/test-data/data\.go$'
  gosec:
    exclude-generated: true
    severity: medium
  varnamelen:
    ignore-type-assert-ok: false
    ignore-map-index-ok: false
    ignore-names:
      - d
  ginkgolinter:
    force-expect-to: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  lll:
    line-length: 150
  copyloopvar:
    check-alias: true

linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - ginkgolinter
    #    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - lll
    - misspell
    - mnd
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wsl
