version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - lll
    - misspell
    - mnd
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tagliatelle
    - testpackage
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wsl
  settings:
    copyloopvar:
      check-alias: true
    ginkgolinter:
      force-expect-to: true
    gosec:
      severity: medium
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 150
    mnd:
      ignored-files:
        - internal/converter/test-data/data\.go$
    nolintlint:
      require-explanation: true
      require-specific: true
    varnamelen:
      ignore-names:
        - d
      ignore-type-assert-ok: false
      ignore-map-index-ok: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: internal/converter/testdata/
      - linters:
          - revive
          - staticcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
