name: test

on:
  push:
  pull_request:

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.20.x", "1.21.x", "oldstable", "stable", ">=1.23"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - run: make go-all-tests

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "junit-report.xml"
        if: always()
